services:
  app:
    build: .
    container_name: doctor_app_staging   # ✅ change name

    depends_on:
      db:
        condition: service_healthy

    expose:
      - "3008"

    env_file:
      - .env

    environment:
      - VIRTUAL_HOST=stgm.automedai.in   # ✅ staging domain
      - LETSENCRYPT_HOST=stgm.automedai.in
      - LETSENCRYPT_EMAIL=tech@automedai.in
      - VIRTUAL_PORT=3008

    restart: always

    networks:
      - default
      - proxy-network

  db:
    image: mysql:8
    container_name: queue_db_staging   # ✅ change name
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: queue_db_staging   # ✅ MUST match .env

    ports:
      - "3312:3306"   # ✅ different from production (3311)

    volumes:
      - db_data_staging:/var/lib/mysql   # ✅ separate volume

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data_staging:

networks:
  default:
  proxy-network:
    external: true
    name: fm-global-frontend-network
